### ISSUE TITLE
[pinned] Package npm name transfer with official "react-native-scandit" by scandit

### ISSUE THREAD

**Issue by D1no** [shoplinksys/react-native-scandit#3]
Scandit is implementing an [official react-native bridge](https://github.com/Scandit/barcodescanner-sdk-react-native) for the Scandit SDK. As soon this bridge is deemed ready, the npm package namespace `react-native-scandit` should transfer to the official package, while this implementation here will drop back to `react-native-scandit-shoplink` (change of APIs).

Until that point, the official WIP [can be used via git](https://github.com/Scandit/barcodescanner-sdk-react-native/blob/master/docs/integrate.md#add-the-plugin-to-your-project) and we support this package here until the transfer.

**Comment by TomekJurkowski** [comment]
Hello @D1no ,
I'm writing on behalf of Scandit team to let you know that we are finally releasing the official react-native bridge for our SDK. We decided to use `scandit-react-native` namespace (all of our npm packages have the scandit- prefix and we want to maintain the consistency), so no "namespace transfer" will be required :)
We have a huge favour to ask you, though. Could you deprecate you package, so that it would be easier for other users to find the official package, that will be supported by us from now on?

All the best,
Tomek

**Comment by D1no** [comment]
Sorry, I did not see this issue as it’s muted. We’ll update a notice next week (currently not in office).

**Comment by TomekJurkowski** [comment]
Thanks a lot @D1no !
